---
- name: Install tmux
  become: true
  apt:
    name: tmux
    state: present

- name: Install xclip
  become: true
  apt:
    name: xclip
    state: present
  when: tmux_copy_to_system_clipboard

- name: Configure tmux
  become: false
  template:
    src: tmuxconf.j2
    dest: "{{ local_user_homedir }}/.tmux.conf"
    mode: 0644
